# Generated by Django 2.2.3 on 2020-10-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='form',
            name='prefecture',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='都道府県名'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.Tag', verbose_name='タグ'),
        ),
    ]
