# Generated by Django 2.2.3 on 2020-10-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20201020_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid_level',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='日付')),
                ('one', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア1')),
                ('two', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア2')),
                ('three', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア3')),
                ('four', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア4')),
                ('five', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア5')),
                ('six', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア6')),
                ('seven', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア7')),
                ('eight', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア8')),
                ('nine', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア9')),
                ('ten', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア10')),
                ('eleven', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア11')),
                ('twelve', models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], verbose_name='エリア12')),
            ],
        ),
    ]
