# Generated by Django 2.2.3 on 2020-10-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_covid_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_level',
            name='thirteen',
            field=models.IntegerField(choices=[(1, '危険度1'), (2, '危険度2'), (3, '危険度3'), (4, '危険度4'), (5, '危険度5')], default=1, verbose_name='エリア13'),
        ),
    ]
