# Generated by Django 2.2.3 on 2020-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_covid_level_thirteen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='prefecture',
        ),
        migrations.AddField(
            model_name='form',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='市町村名'),
        ),
    ]
